on:
  push:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clear Cache
        run: rimraf .next
      - name: Build
        run: next build
      - name: Deploy
        uses: vercel/action@v20.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
