name: On Create Store
run-name: User is creating a new store 🚀
on: 
  repository_dispatch:
    types: 
      - on-create-store
permissions:
  contents: write
jobs:
  checkout-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and push new branch
        run: |
          git checkout -b ${{ github.event.client_payload.branch }}
          git config --global user.email "jessie@fstln.io"
          git config --global user.name "jessiefandb"
          git commit --allow-empty -m "Empty commit"
          git push origin ${{ github.event.client_payload.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}